# Generated by Django 3.2.4 on 2021-07-06 15:56

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zigida.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=zigida.core.utils.randcode_gen, max_length=100, verbose_name='CODE')),
                ('sender', models.CharField(blank=True, max_length=100, null=True, verbose_name='SENDER')),
                ('receiver', models.CharField(blank=True, max_length=100, null=True, verbose_name='RECEIVER')),
                ('subject', models.CharField(blank=True, max_length=100, null=True, verbose_name='SUBJECT')),
                ('message', models.CharField(blank=True, max_length=250, null=True, verbose_name='MESSAGE')),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('DE', 'German'), ('PT', 'Portuguese'), ('ES', 'Spanish')], default='FR', max_length=3, verbose_name='LANGUAGE')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emails', to='locations.location')),
            ],
            options={
                'verbose_name_plural': 'emails',
                'db_table': 'emails',
            },
        ),
    ]
