# Generated by Django 3.2.4 on 2021-07-06 15:56

from django.db import migrations, models
import uuid
import zigida.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=zigida.core.utils.refund_randcode_gen, max_length=100, verbose_name='CODE')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='PHONE NUMBER')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='EMAIL')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='REASON')),
                ('refund_status', models.BooleanField(choices=[(1, 'Processed'), (2, 'Cancelled'), (3, 'Completed')], null=True, verbose_name='REFUND STATUS')),
            ],
            options={
                'verbose_name_plural': 'refunds',
                'db_table': 'refunds',
            },
        ),
    ]
