# Generated by Django 3.2.4 on 2021-07-06 15:56

from django.db import migrations, models
import uuid
import zigida.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SRIssue',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID CODE')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=zigida.core.utils.randcode_gen, max_length=100, verbose_name='CODE')),
                ('title', models.CharField(blank=True, max_length=250, null=True, verbose_name='TITLE')),
                ('description', models.TextField(blank=True, null=True, verbose_name='DESCRIPTION')),
                ('dev_note', models.TextField(blank=True, null=True, verbose_name='DEVELOPER NOTE')),
                ('language', models.CharField(choices=[('EN', 'English'), ('FR', 'French'), ('DE', 'German'), ('PT', 'Portuguese'), ('ES', 'Spanish')], default='FR', max_length=3, verbose_name='LANGUAGE')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Bug'), (2, 'Enhancement')], default=1, verbose_name='TYPE')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Assigned'), (2, 'Resolved'), (3, 'Closed')], null=True, verbose_name='STATUS')),
            ],
            options={
                'verbose_name_plural': 'sr_issues',
                'db_table': 'sr_issues',
            },
        ),
    ]
