# Generated by Django 3.2.4 on 2021-07-06 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='qty_color',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='QUANTITY BY COLOR'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_size',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='QUANTITY BY SIZE'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_sold',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='QUANTITY SOLD'),
        ),
        migrations.AddField(
            model_name='product',
            name='qty_stock',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MaxValueValidator(999)], verbose_name='FULL STOCK'),
        ),
    ]
