# Generated by Django 3.2.4 on 2021-07-08 16:47

import django.contrib.postgres.fields
from django.db import migrations, models
import zigida.apps.db.products.products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210706_2237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bool_active',
        ),
        migrations.RemoveField(
            model_name='product',
            name='customer',
        ),
        migrations.AddField(
            model_name='product',
            name='bool_in_stock',
            field=models.BooleanField(default=True, verbose_name='IS IN STOCK'),
        ),
        migrations.AddField(
            model_name='product',
            name='bool_new',
            field=models.BooleanField(default=True, verbose_name='IS NEW'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999, verbose_name='COLOR'), default=zigida.apps.db.products.products.models.categories_array, null=True, size=None),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999, verbose_name='SIZE'), default=zigida.apps.db.products.products.models.categories_array, null=True, size=None),
        ),
    ]
