# Generated by Django 3.2.4 on 2021-07-09 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20210708_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='bool_new',
        ),
    ]
