# Generated by Django 3.2.4 on 2021-07-06 15:56

from django.db import migrations, models
import uuid
import zigida.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=zigida.core.utils.receipt_randcode_gen, max_length=100, verbose_name='CODE')),
                ('amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=15, null=True, verbose_name='AMOUNT')),
                ('payment_type', models.CharField(choices=[(1, 'Mobile Money'), (2, 'Credit Card'), (3, 'Debit Card'), (4, 'Bank Transfer'), (5, 'Paypal'), (6, 'Skrill')], max_length=2, null=True, verbose_name='PAYMENT TYPE')),
            ],
            options={
                'verbose_name_plural': 'receipts',
                'db_table': 'receipts',
            },
        ),
    ]
