# Generated by Django 3.2.4 on 2021-07-06 15:56

from django.db import migrations, models
import django.db.models.deletion
import uuid
import zigida.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=zigida.core.utils.categ_randcode_gen, max_length=100, verbose_name='CODE')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='TITLE')),
                ('Description', models.TextField(blank=True, null=True, verbose_name='DESCRIPTION')),
                ('sub', models.BooleanField(blank=True, default=True, null=True, verbose_name='SUB-CATEGORY')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='categories', to='categories.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
    ]
