# Generated by Django 3.2.4 on 2021-07-09 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='bool_men',
            field=models.BooleanField(default=True, verbose_name='IS MEN PRODUCT'),
        ),
        migrations.AddField(
            model_name='category',
            name='bool_new',
            field=models.BooleanField(default=True, verbose_name='IS NEW'),
        ),
    ]
