# Generated by Django 3.2.4 on 2021-07-06 15:56

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid
import zigida.apps.db.stores.stores.models
import zigida.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openinghours', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('street_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Street Name')),
                ('house_number', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Number')),
                ('post_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Postal Code')),
                ('area', models.CharField(blank=True, max_length=100, null=True, verbose_name='Area')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('region', models.CharField(blank=True, max_length=100, null=True, verbose_name='Region')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=zigida.core.utils.store_randcode_gen, max_length=100, verbose_name='CODE')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='NAME')),
                ('employee', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=999, verbose_name='EMPLOYEES'), default=zigida.apps.db.stores.stores.models.employee_array, null=True, size=None)),
                ('bool_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='IS ACTIVE')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to=settings.AUTH_USER_MODEL)),
                ('openinghour', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stores', to='openinghours.openinghour')),
            ],
            options={
                'verbose_name_plural': 'stores',
                'db_table': 'stores',
            },
        ),
    ]
