# Generated by Django 3.2.4 on 2021-07-06 15:56

from decimal import Decimal
from django.conf import settings
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid
import zigida.apps.db.accounting.vouchers.models
import zigida.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_arrary', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9999, verbose_name='ITEMS'), default=zigida.apps.db.accounting.vouchers.models.default_voucher, null=True, size=None)),
                ('order_arrary', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9999, verbose_name='ORDERS'), default=zigida.apps.db.accounting.vouchers.models.default_voucher, null=True, size=None)),
                ('payment_arrary', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9999, verbose_name='PAYMENTS'), default=zigida.apps.db.accounting.vouchers.models.default_voucher, null=True, size=None)),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=zigida.core.utils.randcode_gen, max_length=100, verbose_name='CODE')),
                ('amount', models.DecimalField(decimal_places=5, default=0.0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='VOUCHER AMOUNT')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vouchers', to='locations.location')),
            ],
            options={
                'verbose_name_plural': 'vouchers',
                'db_table': 'vouchers',
            },
        ),
    ]
