# Generated by Django 3.2.4 on 2021-07-06 15:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid
import zigida.apps.db.visitors.models
import zigida.core.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('uuid_code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_key', models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, verbose_name='TOKEN')),
                ('code', models.CharField(default=zigida.core.utils.randcode_gen, max_length=100, verbose_name='CODE')),
                ('pages_arrary', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=9999, verbose_name='PAGES'), default=zigida.apps.db.visitors.models.default_pages, null=True, size=None)),
                ('language', models.CharField(max_length=2, null=True, verbose_name='LANGUAGE')),
                ('app_type', models.CharField(choices=[('1', 'WEB'), ('2', 'API')], max_length=3, null=True, verbose_name='APP TYPE')),
                ('date_created', models.DateField(auto_now_add=True, verbose_name='DATE CREATED')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='DATE UPDATED')),
                ('last_updated_by', models.CharField(blank=True, max_length=50, null=True, verbose_name='LAST UPDATED BY')),
                ('bool_deleted', models.BooleanField(default=False, verbose_name='IS DELETED?')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='visitors', to='locations.location')),
            ],
            options={
                'verbose_name_plural': 'visitors',
                'db_table': 'visitors',
            },
        ),
    ]
